### ISSUE TITLE
Remove Track

### ISSUE THREAD

**Issue by sjlagasse** [tinntinnabulate78/jammming_mh#3]
https://github.com/tinntinnabulate78/jammming_mh/blob/5f130eb45aa7d98c5c4e1fe0bab9b8e8f6671b8d/src/components/App/App.js#L58-L62

This won't work because you are trying to use `filter` on a number. Also, you aren't passing a parameter to the function.

**Comment by tinntinnabulate78** [comment]
Updated removeTrack method.
