### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by sjlagasse** [tinntinnabulate78/jammming_mh#6]
https://github.com/tinntinnabulate78/jammming_mh/blob/5f130eb45aa7d98c5c4e1fe0bab9b8e8f6671b8d/src/components/Playlist/Playlist.js#L24-L26

When you have a component with a lot of props try to indent it like this:

```
<Tracklist
  tracks={this.props.playlistTracks}
  onRemove={this.props.onRemove}
  isRemoval = 'true'
/>
```

**Comment by tinntinnabulate78** [comment]
Updated indentation for lines 24-26.
